### ISSUE TITLE
Why limit projects only to repo.json

### ISSUE THREAD

**Issue by kant2002** [dotnet/issue-labeler#32]
I try to run project using
```
dotnet run --project src/CreateMikLabelModel/CreateMikLabelModel.csproj -- dotnet/wpf
```

and I receiving `CreateMikLabelModel Error: 0 : The repo 'dotnet/wpf' was not found in repos.json`.
I know that `dotnet/wpf` does not collected as part of this project, but why do limit dataset creation to repositories only in `repos.json`?

**Comment by Eilon** [comment]
@kant2002 the tool is cobbled together from random code that a few people wrote, so it's written to support only what a few of us needed at the time it was written 😁 .

We could certainly change it so that _if_ a repo _is_ in `repos.json` then it uses the metadata stored there, and that otherwise it assumes it's a random other repo, and operates with default settings. We do still need `repos.json` because some repos have special requirements (such as using additional repos for training data).
